import Head from 'next/head';
import Image from 'next/image';
import cls from 'classnames';
import styles from '../styles/Home.module.css';
import Hero from '../components/hero/hero.component';
import AboutSection from '../components/about-section/about-section.component';
import FeaturedPortfolio from '../components/featured-portfolio/featured-portfolio.component';
import HowWork from '../components/how-work-section/how-work.component';
import TeamSection from '../components/team-section/team-section.component';
import ExperienceSection from '../components/experience-section/experience-section.component';
import ModalContainer from '../components/modal/modal.component';

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Kazmi Architects</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="main">
        <Hero />
        <AboutSection />
        <FeaturedPortfolio />
        <HowWork />    
        {/* <TeamSection /> */}
        <ExperienceSection />
        <ModalContainer />
      </main>

    
    </div>
  )
}
