import Head from 'next/head';
import styles from '../styles/Portfolio.module.css';
import { TitleWrap } from '../components/title-wrap/title-wrap.component';
import FeaturedPortfolio from '../components/featured-portfolio/featured-portfolio.component.jsx';
import ModalContainer from '../components/modal/modal.component';

export default function Portfolio() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Kazmis Site | Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="main">
        <TitleWrap title="Portfolio" />

        <FeaturedPortfolio />
        <ModalContainer />
      </main>

    
    </div>
  )
}