import Head from 'next/head';
import { useState,useRef,useEffect } from 'react';
import cls from 'classnames';
import styles from '../styles/Services.module.css';
import { TitleWrap } from '../components/title-wrap/title-wrap.component';
import { useGetServicesQuery } from '../state/api';

export default function Services() {
  const [selectedService,setSelectedService]=useState(0);
  const {data,isLoading,isError}=useGetServicesQuery();


  return (
    <div className={styles.container}>
      <Head>
        <title>Kazmis Site | Services</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="main">
        <TitleWrap title="Services" />

        <div className={cls(styles.servicesIntro,'mx-auto max-w-7xl pl-10 pr-10')}>
          <div className={cls('grid md:grid-cols-10 mb-24',styles.servicesContainer)}>
            <div className={cls('text-center col-span-10 md:text-left mb-24 md:mb-10 md:col-span-3',styles.servicesNavContainer)}>
              <h3>Our Services</h3>
              <ul className={cls(styles.servicesNav,'mb-5')}>
              {
                
                data?.data?.map((item, index) => (
                  <li key={index} id='item'
                  className={`${selectedService==index ? styles.selected : styles.notselected}`}
                  onClick={()=> setSelectedService(index)}>
                    {item.attributes.ServiceTitle}
                  </li>
                ))
                }
                </ul>
            </div>
            
            <div className={cls('col-span-7 text-justify selectedService',styles.selectService)}>
                <div className={cls(styles.content,styles.fadeInAnim)}>
                  <div className={cls(styles.entryContent)}>
                    <span>Architecture is about experience</span>
                    <h3 className='text-left'>We are focused on technically complex projects</h3>

                  </div>
                  {data?.data[selectedService]?.attributes.ServiceDescription}
                </div>
            </div>
               
          </div>
        </div>
      </main>

    
    </div>
  )
}
